POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyYXNlbWNsIiwiaWQiOiI2M2RkMjMyZmFmYzQxZmE5ZDdhMDFmM2QiLCJpYXQiOjE2NzU0NTM5MDN9.zi67kua2Lpo4xTBfO4VWG5VGI4VWggbmB7OVWojhz-c

{
	"title": "test with auth token",
	"author": "frasemcl",
	"url": "google.com",
	"likes": 111
}